apiVersion: 1

datasources:
  - name: InfluxDB telegraf
    type: influxdb
    access: proxy
    database: grafana
    user: syudai
    password: password
    url: https://influxdb-service:8086
    jsonData:
      httpMode: GET
      tlsSkipVerify: true
    editable: true